-- Authors: Anthony Arena, Jonathan Anastasiou, John Frederiksen, Daniel Spitzer
--Drop tables 
DROP TABLE Groups CASCADE CONSTRAINTS
DROP TABLE Subtaskbids CASCADE CONSTRAINTS
DROP TABLE Subtasks CASCADE CONSTRAINTS
DROP TABLE Taskbids CASCADE CONSTRAINTS
DROP TABLE Tasks CASCADE CONSTRAINTS
DROP TABLE Users CASCADE CONSTRAINTS
DROP TABLE Locations CASCADE CONSTRAINTS